### PR TITLE
Use actual app name as user agent, instead of browser's one

### PR DESCRIPTION
**Pull request by hdk5**
It seems that volve doesn't care for it, but it might solve being banned on heroku problem.

### CODE REVIEW

**Comment by South-Paw** [comment]
I'm unsure how this fixes anything on the Heroku end - do they care about these sort of things or something?

If the Steam API doesn't care about this header key, we'd be better to remove it completely 🤔

**Comment by JourneyOver** [comment]
Yes heroku cares about the header lol.. So many people have been getting their app suspended or having it just shut down today in discord becuase of header issues.

```
Use the Service to access a third party web property for the purposes of web scraping, web crawling, web monitoring, or other similar activity through a web client that does not take commercially reasonable efforts to:
identify itself via a unique User Agent string describing the purpose of the web client; and
obey the robots exclusion standard (also known as the robots.txt standard), including the crawl-delay directive;
```

is the exact quotes from the Acceptable Use Policy of heroku. https://www.heroku.com/policy/aup under `Prohibited Actions`

**Review by South-Paw — DISMISSED** [review]

**Comment by South-Paw** [comment]
[Looks like xPaw has rejected the PR for the PHP end](https://github.com/SteamDatabase/SalienCheat/pull/227) - is anyone aware of any adverse reactions to doing this?

Only one I can see is Valve potentially blocking our specific user-agent header which could break the script for everyone at a moments notice...

@JourneyOver @hdk5 @resir014 thoughts?

**Comment by JourneyOver** [comment]
My thoughts have been expressed in PM's on discord since we was already talking in there ^^

**Comment by South-Paw** [comment]
Could always PR it in and let people use it at their own risk by having to enable it (and having some clear warnings around it)

**Comment by JourneyOver** [comment]
Yea you could do that, probably would be the best bet if you are hesitant about valve doing something.

**Comment by ghost** [comment]
I would suggest just having a config to toggle the user-agent, as you said. xPaw rejected the PR because they didn't want any more Heroku-specific stuff.

As far as if this would have effect with Heroku, it's likely since I contacted them about my suspension and they said it was because it violated rule 21, which encompassed user-agents.

**Comment by hdk5** [comment]
Looks like xPaw changed UA in his script 

https://github.com/SteamDatabase/SalienCheat/commit/2954a4b10e46525ac692f47bf87fc8c323a8068d

**Comment by JourneyOver** [comment]
and now just seems heroku doesn't like anything to do with salien scripts >.<

**Pull request closed without merging**
