### PR TITLE
Added Dockerfile

### PR DESCRIPTION
**Pull request by mhajder**
You can use that command:
`docker run -it --init --rm --name salien salien-script-js:latest` Default: node cli.js --help

`docker run -it --init --rm --name salien salien-script-js:latest --token xxxxxxxx` etc

You could do automatic builds.

### CODE REVIEW

**Comment by South-Paw** [comment]
Awesome! Is there anything we should add to the readme to let people know its a feature?

**Comment by mhajder** [comment]
So many things, but first we have to configure automatic docker image building.

**Comment by South-Paw** [comment]
Is that something we can just PR in? I assume we need this in first? (I'm very rough with docker and only know the basics)

**Review by South-Paw — APPROVED** [review]

**Comment by mhajder** [comment]
**Merge this.**
First connect you docker profile with Github.
https://docs.docker.com/docker-hub/github/#linking-docker-hub-to-a-github-account
Then go to this page:
https://hub.docker.com/add/automated-build/github/
Click text: *Click here to customize*
And set this:
image
`/^v[0-9.]+$/`

**Comment by resir014** [comment]
@South-Paw I've done a bit of dockering at work, I can help with the readme a bit.

Awesome work @Rzeszow! This can be merged. :+1:

**Pull request merged**
