### PR TITLE
Fix boss zone

### LINKED ISSUE #52: Not working at Boss zone
https://imgur.com/a/yXf4dxb

### PR DESCRIPTION
**Pull request by welwood08**
Minor adjustments needed to make boss combat functional.

Fixes #52

### CODE REVIEW

**Review by South-Paw — APPROVED** [review]

**Comment by South-Paw** [comment]
@welwood08 did you get a chance to test these while there was a boss up at all 😟 

wondering if we know it works or we think it works.

**Comment by welwood08** [comment]
I was racing to get it working while there was a boss zone active, but it was over 97% captured so I'm not sure if there aren't other problems since all I saw was waiting messages once I'd got it this far.

**Comment by South-Paw** [comment]
@welwood08 okay, I've only just woken up and missed it all ... really sorry it didn't work first time round but thank you so much for proposing these changes.

Let's get them merged and I'll dig into it a bit more to see what/if anything else is wrong

**Comment by C0rn3j** [comment]
@South-Paw boss is on, script doesn't work. Sorry for not taking proper logs, I switched to SteamDB's script ASAP.

```
[01:00:07] >> Selected Next Zone 63 on Planet 38 (Captured: 62.91% - Difficulty: BOSS - Easy)

[01:00:08] @@ Boss -- HP: 36965272/50000000 - Lasers: 5 - Team Heals: 57

[01:00:08] @@ Boss -- Waiting...
[01:00:12] @@ Boss -- Waiting...
[01:00:15] @@ Boss -- HP: 36839442/50000000 - Lasers: 5 - Team Heals: 58

[01:00:15] @@ Boss -- Waiting...
[01:00:18] @@ Boss -- Waiting...
[01:00:22] @@ Boss -- HP: 36713623/50000000 - Lasers: 5 - Team Heals: 61

[01:00:22] @@ Boss -- Waiting...
[01:00:25] @@ Boss -- HP: 36587808/50000000 - Lasers: 5 - Team Heals: 61

[01:00:25] @@ Boss -- Waiting...
[01:00:29] @@ Boss -- Waiting...
[01:00:32] @@ Boss -- HP: 36336183/50000000 - Lasers: 6 - Team Heals: 61

[01:00:32] @@ Boss -- Waiting...
[01:00:35] @@ Boss -- Waiting...
[01:00:39] @@ Boss -- HP: 36210362/50000000 - Lasers: 6 - Team Heals: 61

[01:00:39] SalienScriptRestart: Boss battle had too many errors!
[01:00:39]  Script will restart in 5 seconds... 

```

```
[01:01:17] >> Selected Next Zone 63 on Planet 38 (Captured: 64.42% - Difficulty: BOSS - Easy)

[01:01:18] @@ Boss -- HP: 35329621/50000000 - Lasers: 7 - Team Heals: 57

[01:01:18] @@ Boss -- Waiting...
[01:01:21] @@ Boss -- Waiting...
[01:01:25] @@ Boss -- HP: 35077997/50000000 - Lasers: 8 - Team Heals: 59

[01:01:25] @@ Boss -- Waiting...
[01:01:28] @@ Boss -- HP: 34952187/50000000 - Lasers: 8 - Team Heals: 59

[01:01:28] @@ Boss -- Waiting...
[01:01:32] @@ Boss -- Waiting...
[01:01:35] @@ Boss -- HP: 34776038/50000000 - Lasers: 8 - Team Heals: 62

[01:01:35] @@ Boss -- Waiting...
[01:01:38] @@ Boss -- Waiting...
[01:01:42] @@ Boss -- HP: 34700540/50000000 - Lasers: 8 - Team Heals: 63

[01:01:42] FetchError: For ITerritoryControlMinigameService/ReportBossDamage/v0001
{
  "message": "invalid json response body at https://community.steam-api.com/ITerritoryControlMinigameService/ReportBossDamage/v0001/?access_token=58d77b661cb610c42b6b8b009d4c39f2&use_heal_ability=0&damage_to_boss=1&damage_taken=0 reason: Unexpected token < in JSON at position 0", 
  "type": "invalid-json"
}
[01:01:42] Retrying ITerritoryControlMinigameService/ReportBossDamage/v0001 in 3 seconds...
[01:01:45] @@ Boss -- HP: 34574725/50000000 - Lasers: 8 - Team Heals: 64

[01:01:45] @@ Boss -- Waiting...
[01:01:48] @@ Boss -- Waiting...
[01:01:52] @@ Boss -- HP: 34448905/50000000 - Lasers: 9 - Team Heals: 70

[01:01:52] SalienScriptRestart: Boss battle had too many errors!
[01:01:52]  Script will restart in 5 seconds... 
```

**Comment by South-Paw** [comment]
@C0rn3j please avoid commenting on old PRs or issues as it makes things really hard to track.

When it says `Boss battle had too many errors!` that's because the max errors allowed variable is not being cleared when a request succeeds - it currently gets 10 errors total (in a row or not) and restarts as it should when an exception is thrown.

While I know this is/was not ideal, it is as far as I know, playing the boss zones correctly

**Pull request merged**
